/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateStoreInput = {
  id?: string | null,
  store_name: string,
  phone?: string | null,
  region_id?: number | null,
  longitude?: string | null,
  latitude?: string | null,
  status?: number | null,
  start_time?: string | null,
  end_time?: string | null,
  sort?: number | null,
  keywords?: string | null,
  logo?: string | null,
  like?: number | null,
  clicks?: number | null,
  reviews?: number | null,
  store_desc?: string | null,
  created_at?: number | null,
  updated_at?: number | null,
  is_buy?: number | null,
  shop_url?: string | null,
  _version?: number | null,
};

export type ModelStoreConditionInput = {
  store_name?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  region_id?: ModelIntInput | null,
  longitude?: ModelStringInput | null,
  latitude?: ModelStringInput | null,
  status?: ModelIntInput | null,
  start_time?: ModelStringInput | null,
  end_time?: ModelStringInput | null,
  sort?: ModelIntInput | null,
  keywords?: ModelStringInput | null,
  logo?: ModelStringInput | null,
  like?: ModelIntInput | null,
  clicks?: ModelIntInput | null,
  reviews?: ModelIntInput | null,
  store_desc?: ModelStringInput | null,
  created_at?: ModelIntInput | null,
  updated_at?: ModelIntInput | null,
  is_buy?: ModelIntInput | null,
  shop_url?: ModelStringInput | null,
  and?: Array< ModelStoreConditionInput | null > | null,
  or?: Array< ModelStoreConditionInput | null > | null,
  not?: ModelStoreConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Store = {
  __typename: "Store",
  id: string,
  store_name: string,
  phone?: string | null,
  region_id?: number | null,
  longitude?: string | null,
  latitude?: string | null,
  status?: number | null,
  start_time?: string | null,
  end_time?: string | null,
  sort?: number | null,
  keywords?: string | null,
  logo?: string | null,
  like?: number | null,
  clicks?: number | null,
  reviews?: number | null,
  store_desc?: string | null,
  created_at?: number | null,
  updated_at?: number | null,
  is_buy?: number | null,
  shop_url?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateStoreInput = {
  id: string,
  store_name?: string | null,
  phone?: string | null,
  region_id?: number | null,
  longitude?: string | null,
  latitude?: string | null,
  status?: number | null,
  start_time?: string | null,
  end_time?: string | null,
  sort?: number | null,
  keywords?: string | null,
  logo?: string | null,
  like?: number | null,
  clicks?: number | null,
  reviews?: number | null,
  store_desc?: string | null,
  created_at?: number | null,
  updated_at?: number | null,
  is_buy?: number | null,
  shop_url?: string | null,
  _version?: number | null,
};

export type DeleteStoreInput = {
  id: string,
  _version?: number | null,
};

export type ModelStoreFilterInput = {
  id?: ModelIDInput | null,
  store_name?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  region_id?: ModelIntInput | null,
  longitude?: ModelStringInput | null,
  latitude?: ModelStringInput | null,
  status?: ModelIntInput | null,
  start_time?: ModelStringInput | null,
  end_time?: ModelStringInput | null,
  sort?: ModelIntInput | null,
  keywords?: ModelStringInput | null,
  logo?: ModelStringInput | null,
  like?: ModelIntInput | null,
  clicks?: ModelIntInput | null,
  reviews?: ModelIntInput | null,
  store_desc?: ModelStringInput | null,
  created_at?: ModelIntInput | null,
  updated_at?: ModelIntInput | null,
  is_buy?: ModelIntInput | null,
  shop_url?: ModelStringInput | null,
  and?: Array< ModelStoreFilterInput | null > | null,
  or?: Array< ModelStoreFilterInput | null > | null,
  not?: ModelStoreFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelStoreConnection = {
  __typename: "ModelStoreConnection",
  items:  Array<Store | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type CreateStoreMutationVariables = {
  input: CreateStoreInput,
  condition?: ModelStoreConditionInput | null,
};

export type CreateStoreMutation = {
  createStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateStoreMutationVariables = {
  input: UpdateStoreInput,
  condition?: ModelStoreConditionInput | null,
};

export type UpdateStoreMutation = {
  updateStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteStoreMutationVariables = {
  input: DeleteStoreInput,
  condition?: ModelStoreConditionInput | null,
};

export type DeleteStoreMutation = {
  deleteStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type GetStoreQueryVariables = {
  id: string,
};

export type GetStoreQuery = {
  getStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListStoresQueryVariables = {
  filter?: ModelStoreFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListStoresQuery = {
  listStores?:  {
    __typename: "ModelStoreConnection",
    items:  Array< {
      __typename: "Store",
      id: string,
      store_name: string,
      phone?: string | null,
      region_id?: number | null,
      longitude?: string | null,
      latitude?: string | null,
      status?: number | null,
      start_time?: string | null,
      end_time?: string | null,
      sort?: number | null,
      keywords?: string | null,
      logo?: string | null,
      like?: number | null,
      clicks?: number | null,
      reviews?: number | null,
      store_desc?: string | null,
      created_at?: number | null,
      updated_at?: number | null,
      is_buy?: number | null,
      shop_url?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncStoresQueryVariables = {
  filter?: ModelStoreFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncStoresQuery = {
  syncStores?:  {
    __typename: "ModelStoreConnection",
    items:  Array< {
      __typename: "Store",
      id: string,
      store_name: string,
      phone?: string | null,
      region_id?: number | null,
      longitude?: string | null,
      latitude?: string | null,
      status?: number | null,
      start_time?: string | null,
      end_time?: string | null,
      sort?: number | null,
      keywords?: string | null,
      logo?: string | null,
      like?: number | null,
      clicks?: number | null,
      reviews?: number | null,
      store_desc?: string | null,
      created_at?: number | null,
      updated_at?: number | null,
      is_buy?: number | null,
      shop_url?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreateStoreSubscription = {
  onCreateStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateStoreSubscription = {
  onUpdateStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteStoreSubscription = {
  onDeleteStore?:  {
    __typename: "Store",
    id: string,
    store_name: string,
    phone?: string | null,
    region_id?: number | null,
    longitude?: string | null,
    latitude?: string | null,
    status?: number | null,
    start_time?: string | null,
    end_time?: string | null,
    sort?: number | null,
    keywords?: string | null,
    logo?: string | null,
    like?: number | null,
    clicks?: number | null,
    reviews?: number | null,
    store_desc?: string | null,
    created_at?: number | null,
    updated_at?: number | null,
    is_buy?: number | null,
    shop_url?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
